### ISSUE TITLE
You can use the official GraphDB docker image directly when using the Free edition, it does not require to download the zip from the email

### ISSUE THREAD

**Issue by vemonet** [markwilkinson/FAIR-in-a-box#4]
Hi @markwilkinson , GraphDB recently updated how they distribute their free version, and we don't need to go through the licensing email and rebuilding the image: https://hub.docker.com/r/ontotext/graphdb/

> Since GraphDB 10.0, there's a single docker image for all editions of GraphDB. The usage restrictions come from the applied license (or lack of license in case of the free version).

So starting from v10 you can now just pull the image from dockerhub, e.g. `ontotext/graphdb:10.1.0`

This will make it much easier for your users to get the stack up and running :)

**Comment by markwilkinson** [comment]
We've been using that for.... months :-)

**Comment by vemonet** [comment]
Nice, but the readme is sill documenting the old cumbersome process :)

**Comment by markwilkinson** [comment]
Indeed... and that is why the first instruction on that page is "DO NOT USE! DEPRECATED!!!
